// Interface catalog. Regional spelling/script choices are explicit; no dialect inference.
const WaveLocales = (() => {
  const keys = ['Accueil','Rechercher','Bibliothèque','Importer','Récemment joués','Tout','Favoris','Playlists','Paramètres','Compte','Affichage','Langues','Mentions légales','Jour (clair)','Nuit (sombre)','Retour','Fermer','Annuler','Sauvegarder','Modifier','Trier','Titre','Artiste','Durée','Note','Tri personnalisé','Aléatoire','Ajouter des morceaux','Nouvelle playlist','Renommer','Supprimer','Retirer','Tout sélectionner','Tout désélectionner','Choisir des fichiers','Glisse tes fichiers audio ici','ou','Aucun morceau joué récemment.','Aucun morceau importé.','Aucun favori.','Aucun résultat.','Rechercher une langue','Langue de l’appareil','Rechercher dans la bibliothèque...','Rechercher sur YouTube...','Confidentialité','Informations légales et conditions d’utilisation','Lecture','Pause','Précédent','Suivant','Ajouter aux favoris','Retirer des favoris'];
  const rows = {
    en: 'Home|Search|Library|Import|Recently played|All|Favorites|Playlists|Settings|Account|Appearance|Languages|Legal|Light|Dark|Back|Close|Cancel|Save|Edit|Sort|Title|Artist|Duration|Rating|Custom order|Shuffle|Add tracks|New playlist|Rename|Delete|Remove|Select all|Deselect all|Choose files|Drop your audio files here|or|No recently played tracks.|No imported tracks.|No favorites.|No results.|Search languages|Device language|Search your library...|Search YouTube...|Privacy|Legal information and terms of use|Play|Pause|Previous|Next|Add to favorites|Remove from favorites',
    es: 'Inicio|Buscar|Biblioteca|Importar|Escuchado recientemente|Todo|Favoritos|Listas de reproducción|Ajustes|Cuenta|Apariencia|Idiomas|Aviso legal|Claro|Oscuro|Volver|Cerrar|Cancelar|Guardar|Editar|Ordenar|Título|Artista|Duración|Valoración|Orden personalizado|Aleatorio|Añadir canciones|Nueva lista|Cambiar nombre|Eliminar|Quitar|Seleccionar todo|Deseleccionar todo|Elegir archivos|Arrastra aquí tus archivos de audio|o|No has escuchado canciones recientemente.|No hay canciones importadas.|No hay favoritos.|Sin resultados.|Buscar un idioma|Idioma del dispositivo|Buscar en tu biblioteca...|Buscar en YouTube...|Privacidad|Información legal y condiciones de uso|Reproducir|Pausa|Anterior|Siguiente|Añadir a favoritos|Quitar de favoritos',
    ar: 'الرئيسية|بحث|المكتبة|استيراد|المشغّلة مؤخرًا|الكل|المفضلة|قوائم التشغيل|الإعدادات|الحساب|المظهر|اللغات|المعلومات القانونية|فاتح|داكن|رجوع|إغلاق|إلغاء|حفظ|تعديل|ترتيب|العنوان|الفنان|المدة|التقييم|ترتيب مخصص|تشغيل عشوائي|إضافة مقاطع|قائمة تشغيل جديدة|إعادة تسمية|حذف|إزالة|تحديد الكل|إلغاء تحديد الكل|اختيار ملفات|اسحب ملفات الصوت إلى هنا|أو|لا توجد مقاطع مشغّلة مؤخرًا.|لا توجد مقاطع مستوردة.|لا توجد مفضلة.|لا توجد نتائج.|البحث عن لغة|لغة الجهاز|البحث في المكتبة...|البحث في YouTube...|الخصوصية|المعلومات القانونية وشروط الاستخدام|تشغيل|إيقاف مؤقت|السابق|التالي|إضافة إلى المفضلة|إزالة من المفضلة',
    'pt-PT': 'Início|Pesquisar|Biblioteca|Importar|Reproduzidas recentemente|Tudo|Favoritos|Listas de reprodução|Definições|Conta|Aspeto|Idiomas|Informações legais|Claro|Escuro|Voltar|Fechar|Cancelar|Guardar|Editar|Ordenar|Título|Artista|Duração|Classificação|Ordem personalizada|Aleatório|Adicionar faixas|Nova lista|Mudar o nome|Eliminar|Remover|Selecionar tudo|Desmarcar tudo|Escolher ficheiros|Arrasta os teus ficheiros de áudio para aqui|ou|Nenhuma faixa reproduzida recentemente.|Nenhuma faixa importada.|Sem favoritos.|Sem resultados.|Pesquisar idioma|Idioma do dispositivo|Pesquisar na biblioteca...|Pesquisar no YouTube...|Privacidade|Informações legais e termos de utilização|Reproduzir|Pausa|Anterior|Seguinte|Adicionar aos favoritos|Remover dos favoritos',
    'pt-BR': 'Início|Buscar|Biblioteca|Importar|Tocadas recentemente|Tudo|Favoritos|Playlists|Configurações|Conta|Aparência|Idiomas|Informações legais|Claro|Escuro|Voltar|Fechar|Cancelar|Salvar|Editar|Ordenar|Título|Artista|Duração|Avaliação|Ordem personalizada|Aleatório|Adicionar músicas|Nova playlist|Renomear|Excluir|Remover|Selecionar tudo|Desmarcar tudo|Escolher arquivos|Arraste seus arquivos de áudio para cá|ou|Nenhuma música tocada recentemente.|Nenhuma música importada.|Nenhum favorito.|Nenhum resultado.|Buscar idioma|Idioma do dispositivo|Buscar na biblioteca...|Buscar no YouTube...|Privacidade|Informações legais e termos de uso|Reproduzir|Pausar|Anterior|Próxima|Adicionar aos favoritos|Remover dos favoritos',
    'zh-Hans': '首页|搜索|音乐库|导入|最近播放|全部|收藏|播放列表|设置|账户|外观|语言|法律信息|浅色|深色|返回|关闭|取消|保存|编辑|排序|标题|艺人|时长|评分|自定义排序|随机播放|添加歌曲|新建播放列表|重命名|删除|移除|全选|取消全选|选择文件|将音频文件拖到此处|或|暂无最近播放的歌曲。|暂无已导入的歌曲。|暂无收藏。|没有结果。|搜索语言|设备语言|搜索音乐库…|搜索 YouTube…|隐私|法律信息和使用条款|播放|暂停|上一首|下一首|添加到收藏|取消收藏',
    'zh-Hant': '首頁|搜尋|音樂庫|匯入|最近播放|全部|收藏|播放清單|設定|帳號|外觀|語言|法律資訊|淺色|深色|返回|關閉|取消|儲存|編輯|排序|標題|藝人|長度|評分|自訂排序|隨機播放|新增歌曲|新增播放清單|重新命名|刪除|移除|全選|取消全選|選擇檔案|將音訊檔案拖曳至此|或|尚無最近播放的歌曲。|尚無已匯入的歌曲。|尚無收藏。|沒有結果。|搜尋語言|裝置語言|搜尋音樂庫…|搜尋 YouTube…|隱私|法律資訊與使用條款|播放|暫停|上一首|下一首|加入收藏|取消收藏',
    ko: '홈|검색|라이브러리|가져오기|최근 재생|전체|즐겨찾기|플레이리스트|설정|계정|화면 설정|언어|법적 고지|라이트|다크|뒤로|닫기|취소|저장|편집|정렬|제목|아티스트|재생 시간|평점|사용자 지정 순서|셔플|곡 추가|새 플레이리스트|이름 변경|삭제|제거|모두 선택|선택 모두 해제|파일 선택|오디오 파일을 여기에 끌어다 놓으세요|또는|최근 재생한 곡이 없습니다.|가져온 곡이 없습니다.|즐겨찾기가 없습니다.|검색 결과가 없습니다.|언어 검색|기기 언어|라이브러리 검색...|YouTube 검색...|개인정보 보호|법적 정보 및 이용약관|재생|일시 정지|이전|다음|즐겨찾기에 추가|즐겨찾기에서 제거',
    ja: 'ホーム|検索|ライブラリ|インポート|最近再生した曲|すべて|お気に入り|プレイリスト|設定|アカウント|表示|言語|法的情報|ライト|ダーク|戻る|閉じる|キャンセル|保存|編集|並べ替え|タイトル|アーティスト|再生時間|評価|カスタム順|シャッフル|曲を追加|新規プレイリスト|名前を変更|削除|リストから削除|すべて選択|選択をすべて解除|ファイルを選択|音声ファイルをここにドラッグ|または|最近再生した曲はありません。|インポートした曲はありません。|お気に入りはありません。|結果が見つかりません。|言語を検索|端末の言語|ライブラリを検索…|YouTube を検索…|プライバシー|法的情報と利用規約|再生|一時停止|前へ|次へ|お気に入りに追加|お気に入りから削除',
    de: 'Start|Suchen|Mediathek|Importieren|Zuletzt gehört|Alle|Favoriten|Playlists|Einstellungen|Konto|Darstellung|Sprachen|Rechtliche Hinweise|Hell|Dunkel|Zurück|Schließen|Abbrechen|Speichern|Bearbeiten|Sortieren|Titel|Interpret|Dauer|Bewertung|Eigene Reihenfolge|Zufallswiedergabe|Titel hinzufügen|Neue Playlist|Umbenennen|Löschen|Entfernen|Alle auswählen|Auswahl aufheben|Dateien auswählen|Audiodateien hierher ziehen|oder|Keine zuletzt gehörten Titel.|Keine importierten Titel.|Keine Favoriten.|Keine Ergebnisse.|Sprache suchen|Gerätesprache|Mediathek durchsuchen...|Auf YouTube suchen...|Datenschutz|Rechtliche Informationen und Nutzungsbedingungen|Wiedergabe|Pause|Zurück|Weiter|Zu Favoriten hinzufügen|Aus Favoriten entfernen',
    el: 'Αρχική|Αναζήτηση|Βιβλιοθήκη|Εισαγωγή|Πρόσφατες ακροάσεις|Όλα|Αγαπημένα|Λίστες αναπαραγωγής|Ρυθμίσεις|Λογαριασμός|Εμφάνιση|Γλώσσες|Νομικές πληροφορίες|Φωτεινό|Σκούρο|Πίσω|Κλείσιμο|Ακύρωση|Αποθήκευση|Επεξεργασία|Ταξινόμηση|Τίτλος|Καλλιτέχνης|Διάρκεια|Βαθμολογία|Προσαρμοσμένη σειρά|Τυχαία αναπαραγωγή|Προσθήκη κομματιών|Νέα λίστα|Μετονομασία|Διαγραφή|Αφαίρεση|Επιλογή όλων|Αποεπιλογή όλων|Επιλογή αρχείων|Σύρε τα αρχεία ήχου εδώ|ή|Δεν υπάρχουν πρόσφατες ακροάσεις.|Δεν έχουν εισαχθεί κομμάτια.|Δεν υπάρχουν αγαπημένα.|Δεν βρέθηκαν αποτελέσματα.|Αναζήτηση γλώσσας|Γλώσσα συσκευής|Αναζήτηση στη βιβλιοθήκη...|Αναζήτηση στο YouTube...|Απόρρητο|Νομικές πληροφορίες και όροι χρήσης|Αναπαραγωγή|Παύση|Προηγούμενο|Επόμενο|Προσθήκη στα αγαπημένα|Αφαίρεση από τα αγαπημένα',
    tr: 'Ana sayfa|Ara|Kitaplık|İçe aktar|Son çalınanlar|Tümü|Favoriler|Çalma listeleri|Ayarlar|Hesap|Görünüm|Diller|Yasal bilgiler|Açık|Koyu|Geri|Kapat|İptal|Kaydet|Düzenle|Sırala|Başlık|Sanatçı|Süre|Puan|Özel sıralama|Karışık çal|Parça ekle|Yeni çalma listesi|Yeniden adlandır|Sil|Kaldır|Tümünü seç|Seçimi kaldır|Dosya seç|Ses dosyalarını buraya sürükle|veya|Son çalınan parça yok.|İçe aktarılan parça yok.|Favori yok.|Sonuç bulunamadı.|Dil ara|Cihaz dili|Kitaplıkta ara...|YouTube’da ara...|Gizlilik|Yasal bilgiler ve kullanım koşulları|Çal|Duraklat|Önceki|Sonraki|Favorilere ekle|Favorilerden kaldır',
    ru: 'Главная|Поиск|Медиатека|Импорт|Недавно прослушано|Все|Избранное|Плейлисты|Настройки|Аккаунт|Оформление|Языки|Правовая информация|Светлая|Тёмная|Назад|Закрыть|Отмена|Сохранить|Изменить|Сортировка|Название|Исполнитель|Длительность|Оценка|Свой порядок|Перемешать|Добавить треки|Новый плейлист|Переименовать|Удалить|Убрать|Выбрать всё|Снять выделение|Выбрать файлы|Перетащите аудиофайлы сюда|или|Нет недавно прослушанных треков.|Нет импортированных треков.|Избранного пока нет.|Ничего не найдено.|Поиск языка|Язык устройства|Поиск в медиатеке...|Поиск на YouTube...|Конфиденциальность|Правовая информация и условия использования|Воспроизвести|Пауза|Предыдущий|Следующий|Добавить в избранное|Убрать из избранного',
    sv: 'Hem|Sök|Bibliotek|Importera|Nyligen spelat|Alla|Favoriter|Spellistor|Inställningar|Konto|Utseende|Språk|Juridisk information|Ljust|Mörkt|Tillbaka|Stäng|Avbryt|Spara|Redigera|Sortera|Titel|Artist|Längd|Betyg|Egen ordning|Blanda|Lägg till låtar|Ny spellista|Byt namn|Radera|Ta bort|Markera alla|Avmarkera alla|Välj filer|Dra dina ljudfiler hit|eller|Inga nyligen spelade låtar.|Inga importerade låtar.|Inga favoriter.|Inga resultat.|Sök efter språk|Enhetens språk|Sök i biblioteket...|Sök på YouTube...|Integritet|Juridisk information och användarvillkor|Spela|Pausa|Föregående|Nästa|Lägg till i favoriter|Ta bort från favoriter',
    da: 'Hjem|Søg|Bibliotek|Importér|Senest afspillet|Alle|Favoritter|Playlister|Indstillinger|Konto|Udseende|Sprog|Juridiske oplysninger|Lys|Mørk|Tilbage|Luk|Annuller|Gem|Rediger|Sortér|Titel|Kunstner|Varighed|Bedømmelse|Brugerdefineret rækkefølge|Bland|Tilføj numre|Ny playliste|Omdøb|Slet|Fjern|Vælg alle|Fravælg alle|Vælg filer|Træk dine lydfiler hertil|eller|Ingen nyligt afspillede numre.|Ingen importerede numre.|Ingen favoritter.|Ingen resultater.|Søg efter sprog|Enhedens sprog|Søg i biblioteket...|Søg på YouTube...|Privatliv|Juridiske oplysninger og brugsvilkår|Afspil|Pause|Forrige|Næste|Føj til favoritter|Fjern fra favoritter',
    nb: 'Hjem|Søk|Bibliotek|Importer|Nylig spilt|Alle|Favoritter|Spillelister|Innstillinger|Konto|Utseende|Språk|Juridisk informasjon|Lys|Mørk|Tilbake|Lukk|Avbryt|Lagre|Rediger|Sorter|Tittel|Artist|Varighet|Vurdering|Egendefinert rekkefølge|Tilfeldig avspilling|Legg til spor|Ny spilleliste|Gi nytt navn|Slett|Fjern|Velg alle|Fjern alle valg|Velg filer|Dra lydfilene dine hit|eller|Ingen nylig spilte spor.|Ingen importerte spor.|Ingen favoritter.|Ingen resultater.|Søk etter språk|Enhetens språk|Søk i biblioteket...|Søk på YouTube...|Personvern|Juridisk informasjon og bruksvilkår|Spill av|Pause|Forrige|Neste|Legg til i favoritter|Fjern fra favoritter',
    nn: 'Heim|Søk|Bibliotek|Importer|Nyleg spela|Alle|Favorittar|Spelelister|Innstillingar|Konto|Utsjånad|Språk|Juridisk informasjon|Lys|Mørk|Tilbake|Lukk|Avbryt|Lagre|Rediger|Sorter|Tittel|Artist|Lengd|Vurdering|Eigendefinert rekkjefølgje|Tilfeldig avspeling|Legg til spor|Ny speleliste|Gje nytt namn|Slett|Fjern|Vel alle|Fjern alle val|Vel filer|Dra lydfilene dine hit|eller|Ingen nyleg spela spor.|Ingen importerte spor.|Ingen favorittar.|Ingen resultat.|Søk etter språk|Språket på eininga|Søk i biblioteket...|Søk på YouTube...|Personvern|Juridisk informasjon og bruksvilkår|Spel av|Pause|Førre|Neste|Legg til i favorittar|Fjern frå favorittar',
    is: 'Heim|Leita|Safn|Flytja inn|Nýlega spilað|Allt|Uppáhald|Spilunarlistar|Stillingar|Aðgangur|Útlit|Tungumál|Lagalegar upplýsingar|Ljóst|Dökkt|Til baka|Loka|Hætta við|Vista|Breyta|Raða|Titill|Flytjandi|Lengd|Einkunn|Sérsniðin röðun|Stokka|Bæta við lögum|Nýr spilunarlisti|Endurnefna|Eyða|Fjarlægja|Velja allt|Afvelja allt|Velja skrár|Dragðu hljóðskrárnar þínar hingað|eða|Engin lög spiluð nýlega.|Engin innflutt lög.|Ekkert í uppáhaldi.|Engar niðurstöður.|Leita að tungumáli|Tungumál tækis|Leita í safni...|Leita á YouTube...|Persónuvernd|Lagalegar upplýsingar og notkunarskilmálar|Spila|Gera hlé|Fyrra|Næsta|Bæta við uppáhald|Fjarlægja úr uppáhaldi',
    fo: 'Heim|Leita|Savn|Innflyt|Nýliga spælt|Alt|Yndisløg|Spælilistar|Stillingar|Konta|Útsjónd|Mál|Løgfrøðiligar upplýsingar|Ljóst|Myrkt|Aftur|Lat aftur|Angra|Goym|Broyt|Raða|Heiti|Tónleikari|Longd|Meting|Egin raðfylgja|Tilvildarlig spæling|Legg løg afturat|Nýggjur spælilisti|Broyt navn|Strika|Tak burtur|Vel alt|Frável alt|Vel fílur|Drag ljóðfílurnar higar|ella|Eingi nýliga spæld løg.|Eingi innflutt løg.|Eingi yndisløg.|Eingi úrslit.|Leita eftir máli|Málið á tólinum|Leita í savninum...|Leita á YouTube...|Privatlív|Løgfrøðiligar upplýsingar og nýtslutreytir|Spæl|Steðga fyribils|Fyrra|Næsta|Legg í yndisløg|Tak úr yndisløgum',
    id: 'Beranda|Cari|Koleksi|Impor|Baru diputar|Semua|Favorit|Playlist|Pengaturan|Akun|Tampilan|Bahasa|Informasi hukum|Terang|Gelap|Kembali|Tutup|Batal|Simpan|Edit|Urutkan|Judul|Artis|Durasi|Penilaian|Urutan khusus|Acak|Tambahkan lagu|Playlist baru|Ubah nama|Hapus|Keluarkan|Pilih semua|Batalkan semua pilihan|Pilih berkas|Seret berkas audio ke sini|atau|Belum ada lagu yang diputar.|Belum ada lagu yang diimpor.|Belum ada favorit.|Tidak ada hasil.|Cari bahasa|Bahasa perangkat|Cari di koleksi...|Cari di YouTube...|Privasi|Informasi hukum dan ketentuan penggunaan|Putar|Jeda|Sebelumnya|Berikutnya|Tambahkan ke favorit|Hapus dari favorit'
  };
  const definitions = [
    ['fr','Français','Français · France'],['en','English (US)','Anglais · États-Unis'],['es','Español','Espagnol'],['ar','العربية الفصحى','Arabe standard moderne'],
    ['pt-PT','Português (Portugal)','Portugais · Portugal'],['pt-BR','Português (Brasil)','Portugais · Brésil'],
    ['zh-Hans','简体中文','Chinois écrit · simplifié'],['zh-Hant','繁體中文','Chinois écrit · traditionnel'],
    ['ko','한국어','Coréen · Corée du Sud'],['ja','日本語','Japonais'],['de','Deutsch','Allemand · Allemagne'],['el','Ελληνικά','Grec moderne'],
    ['tr','Türkçe','Turc'],['ru','Русский','Russe'],['sv','Svenska','Suédois'],['da','Dansk','Danois'],
    ['nb','Norsk bokmål','Norvégien · bokmål'],['nn','Norsk nynorsk','Norvégien · nynorsk'],['is','Íslenska','Islandais'],['fo','Føroyskt','Féroïen · bêta'],['id','Bahasa Indonesia','Indonésien']
  ];
  const catalogs = { fr:Object.fromEntries(keys.map(key => [key,key])) };
  for (const [code,row] of Object.entries(rows)) {
    const values = row.split('|');
    if (values.length !== keys.length) throw new Error(`Invalid locale catalog: ${code}`);
    catalogs[code] = Object.fromEntries(keys.map((key,i) => [key,values[i]]));
  }
  return { keys, catalogs, definitions };
})();
